/**
 * 일일 가계부 기본 메뉴
 */

import { MenuItem } from './types'

export const defaultMenu: MenuItem[] = [
  // 돼지고기 (기본 100g)
  {
    id: 'pork-snow',
    name: '눈꽃대패',
    category: 'pork',
    price: 5500,
    gramsPerPortion: 100,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },
  {
    id: 'pork-premium',
    name: '고급대패',
    category: 'pork',
    price: 6500,
    gramsPerPortion: 100,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },
  {
    id: 'pork-old',
    name: '옛날삼겹',
    category: 'pork',
    price: 6500,
    gramsPerPortion: 100,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },
  {
    id: 'pork-neck',
    name: '목살대패',
    category: 'pork',
    price: 6500,
    gramsPerPortion: 100,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },
  {
    id: 'pork-flower',
    name: '꽃삼겹대패',
    category: 'pork',
    price: 6900,
    gramsPerPortion: 100,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },
  {
    id: 'pork-hang',
    name: '항정살',
    category: 'pork',
    price: 7500,
    gramsPerPortion: 100,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },
  {
    id: 'pork-korean',
    name: '한돈삼겹대패',
    category: 'pork',
    price: 7500,
    gramsPerPortion: 100,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },
  {
    id: 'pork-fresh',
    name: '한돈생삼겹살',
    category: 'pork',
    price: 8500,
    gramsPerPortion: 100,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },
  {
    id: 'pork-aged-400',
    name: '육미숙성삼겹살(400g)',
    category: 'pork',
    price: 28000,
    gramsPerPortion: 400,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },
  {
    id: 'pork-aged-600',
    name: '육미숙성삼겹살(600g)',
    category: 'pork',
    price: 41000,
    gramsPerPortion: 600,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },

  // 소고기 (기본 100g)
  {
    id: 'beef-usa',
    name: '우삼겹',
    category: 'beef',
    price: 6900,
    gramsPerPortion: 100,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },
  {
    id: 'beef-chadol',
    name: '돌돌이차돌',
    category: 'beef',
    price: 6900,
    gramsPerPortion: 100,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },

  // 식사류 (원가율 20%)
  {
    id: 'meal-rice',
    name: '공기밥',
    category: 'meal',
    price: 1000,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },
  {
    id: 'meal-doenjang',
    name: '된장찌개',
    category: 'meal',
    price: 2000,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },
  {
    id: 'meal-chadol-doenjang',
    name: '차돌된장찌개',
    category: 'meal',
    price: 3000,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },
  {
    id: 'meal-egg',
    name: '계란찜',
    category: 'meal',
    price: 2500,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },
  {
    id: 'meal-combo',
    name: '계란찜+공기밥+뽀로로제로밀크',
    category: 'meal',
    price: 4900,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },
  {
    id: 'meal-naeng',
    name: '물냉면',
    category: 'meal',
    price: 6000,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },
  {
    id: 'meal-bibim',
    name: '비빔냉면',
    category: 'meal',
    price: 6000,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },
  {
    id: 'meal-raw-egg',
    name: '날달걀',
    category: 'meal',
    price: 500,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },
  {
    id: 'meal-cheese',
    name: '치즈(볶음밥용)',
    category: 'meal',
    price: 2500,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },

  // 주류 (원가율 50%)
  {
    id: 'alcohol-soju',
    name: '소주',
    category: 'alcohol',
    price: 3000,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },
  {
    id: 'alcohol-beer',
    name: '맥주',
    category: 'alcohol',
    price: 4500,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },

  // 음료 (원가율 50%)
  {
    id: 'drink-coke',
    name: '코카콜라',
    category: 'drink',
    price: 2000,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },
  {
    id: 'drink-sprite',
    name: '스프라이트',
    category: 'drink',
    price: 2000,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },
  {
    id: 'drink-fanta',
    name: '환타',
    category: 'drink',
    price: 2000,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },
  {
    id: 'drink-coke-zero',
    name: '코카콜라제로',
    category: 'drink',
    price: 2000,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },
  {
    id: 'drink-water',
    name: '생수',
    category: 'drink',
    price: 1000,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },
  {
    id: 'drink-sparkling',
    name: '탄산수',
    category: 'drink',
    price: 2000,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },
  {
    id: 'drink-orange',
    name: '오렌지주스',
    category: 'drink',
    price: 2500,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },
  {
    id: 'drink-grape',
    name: '포도주스',
    category: 'drink',
    price: 2500,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },
  {
    id: 'drink-pororo-zero',
    name: '뽀로로제로밀크',
    category: 'drink',
    price: 1500,
    enabled: true,
    overrideCostRate: null,
    overrideCostPerGram: null,
  },
]
