import { Hobby } from './hobby-types';

export const HOBBIES: Hobby[] = [
  // 활동적+교류형
  {
    id: 'badminton',
    name: '배드민턴',
    why: '활동적이고 사람들과 함께 즐기기 좋은 스포츠입니다',
    level: '초급',
    cost: '낮음',
    indoor: false,
    soloFriendly: false,
    timePerWeek: '보통',
    starterGuide: '지역 체육관에서 동호회를 찾거나, 친구와 함께 시작하세요. 라켓과 셔틀콕만 있으면 바로 시작 가능합니다.',
    categories: ['active-social'],
  },
  {
    id: 'bowling',
    name: '볼링',
    why: '친구들과 게임처럼 즐기며 몸도 움직일 수 있습니다',
    level: '초급',
    cost: '보통',
    indoor: true,
    soloFriendly: false,
    timePerWeek: '짧음',
    starterGuide: '근처 볼링장에서 하우스볼로 시작하세요. 주 1~2회 정도면 충분하며, 점수가 오르는 재미가 있습니다.',
    categories: ['active-social'],
  },
  {
    id: 'climbing',
    name: '실내 암벽등반',
    why: '몸과 머리를 동시에 쓰는 도전적인 스포츠입니다',
    level: '초급',
    cost: '보통',
    indoor: true,
    soloFriendly: true,
    timePerWeek: '보통',
    starterGuide: '클라이밍 짐에서 1일 체험으로 시작하세요. 장비는 대여 가능하며, 안전교육을 꼭 받으세요.',
    categories: ['active-social', 'active-focus'],
  },
  {
    id: 'dance',
    name: '댄스 (힙합/재즈)',
    why: '음악에 맞춰 몸을 움직이며 스트레스를 풀 수 있습니다',
    level: '초급',
    cost: '보통',
    indoor: true,
    soloFriendly: false,
    timePerWeek: '보통',
    starterGuide: '유튜브로 기본 스텝을 배우거나, 동네 댄스학원 체험 수업을 들어보세요.',
    categories: ['active-social', 'affective'],
  },
  {
    id: 'running-crew',
    name: '러닝 크루',
    why: '달리기를 좋아하는 사람들과 함께 운동하며 동기부여를 받을 수 있습니다',
    level: '초급',
    cost: '낮음',
    indoor: false,
    soloFriendly: false,
    timePerWeek: '보통',
    starterGuide: '인스타그램에서 지역 러닝크루를 찾아보세요. 러닝화만 있으면 시작 가능합니다.',
    categories: ['active-social', 'outdoor'],
  },
  {
    id: 'hiking',
    name: '하이킹/등산',
    why: '자연 속에서 몸을 움직이며 힐링할 수 있습니다',
    level: '초급',
    cost: '낮음',
    indoor: false,
    soloFriendly: true,
    timePerWeek: '짧음',
    starterGuide: '가까운 낮은 산부터 시작하세요. 편한 신발, 물, 간식만 챙기면 됩니다.',
    categories: ['active-social', 'outdoor'],
  },
  {
    id: 'cycling',
    name: '자전거 라이딩',
    why: '바람을 맞으며 달리는 상쾌함을 느낄 수 있습니다',
    level: '초급',
    cost: '보통',
    indoor: false,
    soloFriendly: true,
    timePerWeek: '보통',
    starterGuide: '자전거 대여로 시작해보고, 익숙해지면 본인 자전거를 구매하세요. 헬멧은 필수입니다.',
    categories: ['active-social', 'outdoor'],
  },

  // 안정형+감성형
  {
    id: 'calligraphy',
    name: '캘리그라피',
    why: '글씨를 쓰며 마음을 가다듬고 감성을 표현할 수 있습니다',
    level: '초급',
    cost: '낮음',
    indoor: true,
    soloFriendly: true,
    timePerWeek: '짧음',
    starterGuide: '붓펜과 종이로 시작하세요. 유튜브 강좌나 책으로 기본 획 연습부터 시작합니다.',
    categories: ['calm-affective', 'indoor-hands'],
  },
  {
    id: 'watercolor',
    name: '수채화',
    why: '색과 물의 조화로 감성적인 작품을 만들 수 있습니다',
    level: '초급',
    cost: '낮음',
    indoor: true,
    soloFriendly: true,
    timePerWeek: '보통',
    starterGuide: '기본 수채화 세트(12색)와 수채화지를 구매하세요. 간단한 풍경부터 그려보세요.',
    categories: ['calm-affective', 'indoor-hands'],
  },
  {
    id: 'perfume-making',
    name: '향수 만들기',
    why: '향에 민감한 감각을 살려 나만의 향을 창조할 수 있습니다',
    level: '중급',
    cost: '높음',
    indoor: true,
    soloFriendly: true,
    timePerWeek: '짧음',
    starterGuide: '향수 원데이 클래스로 시작하세요. 기본 노트(탑/미들/베이스)에 대해 배웁니다.',
    categories: ['calm-affective'],
  },
  {
    id: 'aroma',
    name: '아로마 블렌딩',
    why: '향기로 감정을 치유하고 공간을 디자인할 수 있습니다',
    level: '초급',
    cost: '보통',
    indoor: true,
    soloFriendly: true,
    timePerWeek: '짧음',
    starterGuide: '에센셜 오일 5~6종 기본 세트와 디퓨저를 구매하세요. 라벤더, 유칼립투스 등으로 시작.',
    categories: ['calm-affective'],
  },
  {
    id: 'flower-class',
    name: '플라워 클래스',
    why: '꽃을 다루며 아름다움과 감성을 동시에 느낄 수 있습니다',
    level: '초급',
    cost: '높음',
    indoor: true,
    soloFriendly: true,
    timePerWeek: '짧음',
    starterGuide: '근처 플라워샵의 원데이 클래스부터 시작하세요. 꽃꽂이 기본기를 배웁니다.',
    categories: ['calm-affective', 'indoor-hands'],
  },
  {
    id: 'reading-club',
    name: '독서 모임 (소수)',
    why: '책을 읽고 생각을 나누며 조용히 교류할 수 있습니다',
    level: '초급',
    cost: '낮음',
    indoor: true,
    soloFriendly: false,
    timePerWeek: '짧음',
    starterGuide: '온라인 독서 모임이나 동네 서점 북클럽을 찾아보세요. 한 달에 한 권 정도 읽습니다.',
    categories: ['calm-affective', 'calm-social'],
  },

  // 탐색형+실내형
  {
    id: 'diy-kits',
    name: 'DIY 키트',
    why: '다양한 만들기를 체험하며 무엇이 재미있는지 찾을 수 있습니다',
    level: '초급',
    cost: '보통',
    indoor: true,
    soloFriendly: true,
    timePerWeek: '짧음',
    starterGuide: '텀블벅, 오늘의집 등에서 다양한 DIY 키트를 구매해보세요. 양초, 비누, 미니어처 등.',
    categories: ['explore-indoor', 'indoor-hands'],
  },
  {
    id: 'drawing-basics',
    name: '그림 입문',
    why: '부담 없이 그림을 그리며 창의력을 발휘할 수 있습니다',
    level: '초급',
    cost: '낮음',
    indoor: true,
    soloFriendly: true,
    timePerWeek: '보통',
    starterGuide: '스케치북과 연필/색연필로 시작하세요. 30일 드로잉 챌린지를 따라해보세요.',
    categories: ['explore-indoor', 'calm-affective'],
  },
  {
    id: 'ukulele',
    name: '우쿨렐레/피아노 체험',
    why: '악기를 부담 없이 배우며 음악적 감각을 키울 수 있습니다',
    level: '초급',
    cost: '보통',
    indoor: true,
    soloFriendly: true,
    timePerWeek: '보통',
    starterGuide: '우쿨렐레는 5~10만원대로 시작 가능합니다. 유튜브로 C, F, G 코드부터 배우세요.',
    categories: ['explore-indoor', 'calm-affective'],
  },
  {
    id: 'photo-editing',
    name: '사진 후보정',
    why: '사진을 편집하며 시각적 감각을 키울 수 있습니다',
    level: '초급',
    cost: '낮음',
    indoor: true,
    soloFriendly: true,
    timePerWeek: '짧음',
    starterGuide: '스마트폰 앱(스냅시드, VSCO)으로 시작하세요. 무료 프리셋을 활용해보세요.',
    categories: ['explore-indoor', 'indoor-mind'],
  },
  {
    id: '3d-print',
    name: '3D 프린팅 체험',
    why: '디지털 설계를 실물로 만드는 신기한 경험을 할 수 있습니다',
    level: '중급',
    cost: '높음',
    indoor: true,
    soloFriendly: true,
    timePerWeek: '짧음',
    starterGuide: '메이커스페이스나 도서관 3D 프린터 체험 프로그램을 찾아보세요. Thingiverse에서 무료 모델 다운.',
    categories: ['explore-indoor', 'indoor-mind'],
  },

  // 몰입형+논리형
  {
    id: 'coding',
    name: '코딩 (웹앱/파이썬)',
    why: '논리적 사고로 문제를 해결하며 결과물을 만들 수 있습니다',
    level: '중급',
    cost: '낮음',
    indoor: true,
    soloFriendly: true,
    timePerWeek: '김',
    starterGuide: '코드카데미나 생활코딩으로 HTML/CSS부터 시작하세요. 또는 파이썬으로 간단한 자동화 스크립트를.',
    categories: ['focus-logic', 'indoor-mind'],
  },
  {
    id: 'chess',
    name: '체스/바둑',
    why: '전략적 사고와 집중력을 키우는 두뇌 스포츠입니다',
    level: '초급',
    cost: '낮음',
    indoor: true,
    soloFriendly: true,
    timePerWeek: '보통',
    starterGuide: 'chess.com이나 리치ess 앱으로 시작하세요. AI와 연습하며 기본 오프닝을 배웁니다.',
    categories: ['focus-logic', 'indoor-mind'],
  },
  {
    id: 'rubiks-cube',
    name: '큐브/퍼즐',
    why: '손으로 맞추며 집중력과 기억력을 높일 수 있습니다',
    level: '초급',
    cost: '낮음',
    indoor: true,
    soloFriendly: true,
    timePerWeek: '짧음',
    starterGuide: '3×3 큐브 하나만 구매하세요. 유튜브로 CFOP 기초 알고리즘을 배웁니다.',
    categories: ['focus-logic', 'indoor-mind', 'indoor-hands'],
  },
  {
    id: 'plastic-model',
    name: '모델 제작 (프라모델)',
    why: '정교한 손놀림과 완성도에 몰입할 수 있습니다',
    level: '중급',
    cost: '보통',
    indoor: true,
    soloFriendly: true,
    timePerWeek: '보통',
    starterGuide: '건프라(건담 프라모델) HG 등급부터 시작하세요. 니퍼와 사포만 있으면 시작 가능.',
    categories: ['focus-logic', 'indoor-hands'],
  },

  // 교류형+실외형
  {
    id: 'photo-walk',
    name: '사진 동호회 출사',
    why: '사진을 찍으며 사람들과 경험을 공유할 수 있습니다',
    level: '초급',
    cost: '낮음',
    indoor: false,
    soloFriendly: false,
    timePerWeek: '짧음',
    starterGuide: '스마트폰 카메라로 충분합니다. 인스타그램에서 #출사 검색 후 모임에 참여해보세요.',
    categories: ['social-outdoor', 'explore-outdoor'],
  },
  {
    id: 'camping',
    name: '캠핑/백패킹',
    why: '자연 속에서 친구들과 힐링하며 추억을 만들 수 있습니다',
    level: '중급',
    cost: '높음',
    indoor: false,
    soloFriendly: false,
    timePerWeek: '짧음',
    starterGuide: '캠핑장 렌탈 텐트부터 시작하세요. 침낭, 랜턴, 간단한 취사도구가 기본입니다.',
    categories: ['social-outdoor', 'active-outdoor'],
  },
  {
    id: 'fishing',
    name: '낚시 입문',
    why: '여유롭게 자연을 즐기며 사람들과 대화할 수 있습니다',
    level: '초급',
    cost: '보통',
    indoor: false,
    soloFriendly: true,
    timePerWeek: '짧음',
    starterGuide: '낚시터에서 장비 대여 후 체험하세요. 손맛을 느껴보고 장비를 구매하세요.',
    categories: ['social-outdoor', 'calm-outdoor'],
  },
  {
    id: 'frisbee',
    name: '프리스비/피크닉 게임',
    why: '가볍게 즐기며 친구들과 놀 수 있는 야외 활동입니다',
    level: '초급',
    cost: '낮음',
    indoor: false,
    soloFriendly: false,
    timePerWeek: '짧음',
    starterGuide: '프리스비 하나면 충분합니다. 공원에서 친구들과 캐치볼부터 시작하세요.',
    categories: ['social-outdoor', 'active-social'],
  },

  // 손활동+감성형
  {
    id: 'pottery',
    name: '도예',
    why: '흙을 만지며 창조의 즐거움과 힐링을 동시에 느낄 수 있습니다',
    level: '중급',
    cost: '높음',
    indoor: true,
    soloFriendly: true,
    timePerWeek: '보통',
    starterGuide: '공방 원데이 클래스로 시작하세요. 물레 체험 후 핸드빌딩으로 접시나 컵을 만들어보세요.',
    categories: ['hands-affective', 'indoor-hands'],
  },
  {
    id: 'metal-craft',
    name: '금속 공예',
    why: '금속을 다루며 독특한 액세서리나 소품을 만들 수 있습니다',
    level: '중급',
    cost: '높음',
    indoor: true,
    soloFriendly: true,
    timePerWeek: '짧음',
    starterGuide: '반지 만들기 클래스부터 시작하세요. 공방에서 장비와 재료를 제공합니다.',
    categories: ['hands-affective', 'indoor-hands'],
  },
  {
    id: 'leather-craft',
    name: '가죽 공예',
    why: '가죽을 재단하고 바느질하며 나만의 소품을 만들 수 있습니다',
    level: '초급',
    cost: '보통',
    indoor: true,
    soloFriendly: true,
    timePerWeek: '짧음',
    starterGuide: '카드지갑 키트로 시작하세요. 기본 도구(커터, 바늘, 실)만 있으면 시작 가능.',
    categories: ['hands-affective', 'indoor-hands'],
  },
  {
    id: 'baking',
    name: '베이킹',
    why: '맛과 향으로 감성을 자극하며 결과물을 나눌 수 있습니다',
    level: '초급',
    cost: '보통',
    indoor: true,
    soloFriendly: true,
    timePerWeek: '짧음',
    starterGuide: '쿠키부터 시작하세요. 오븐, 계량컵, 볼 정도만 있으면 됩니다. 레시피는 유튜브 참고.',
    categories: ['hands-affective', 'indoor-hands'],
  },
  {
    id: 'candle-making',
    name: '양초 공예',
    why: '향과 색으로 공간을 디자인하는 감성적인 취미입니다',
    level: '초급',
    cost: '낮음',
    indoor: true,
    soloFriendly: true,
    timePerWeek: '짧음',
    starterGuide: '소이왁스, 심지, 향료 기본 키트를 구매하세요. 유리 용기에 녹여 부으면 완성.',
    categories: ['hands-affective', 'indoor-hands'],
  },

  // 머리활동+실내형
  {
    id: 'board-game',
    name: '전략 보드게임',
    why: '전략적 사고와 재미를 동시에 즐길 수 있습니다',
    level: '초급',
    cost: '보통',
    indoor: true,
    soloFriendly: false,
    timePerWeek: '짧음',
    starterGuide: '보드게임 카페에서 체험 후 구매하세요. 스플렌더, 카탄, 티켓투라이드 등 추천.',
    categories: ['mind-indoor', 'indoor-mind'],
  },
  {
    id: 'tcg',
    name: '트레이딩 카드 덱빌드',
    why: '전략적으로 덱을 구성하고 대전하는 재미가 있습니다',
    level: '중급',
    cost: '높음',
    indoor: true,
    soloFriendly: false,
    timePerWeek: '보통',
    starterGuide: '매직 더 개더링이나 유희왕 스타터 덱으로 시작하세요. 커뮤니티에서 룰을 배웁니다.',
    categories: ['mind-indoor', 'indoor-mind', 'focus-logic'],
  },
  {
    id: 'data-journal',
    name: '데이터 저널링',
    why: '숫자로 나를 기록하고 분석하는 체계적인 취미입니다',
    level: '초급',
    cost: '낮음',
    indoor: true,
    soloFriendly: true,
    timePerWeek: '짧음',
    starterGuide: '노션이나 엑셀로 일일 기록 템플릿을 만드세요. 수면, 기분, 운동 등을 기록합니다.',
    categories: ['mind-indoor', 'indoor-mind', 'focus-logic'],
  },
  {
    id: 'electronics',
    name: '전자공작 입문',
    why: 'LED, 센서 등으로 간단한 전자기기를 만들 수 있습니다',
    level: '중급',
    cost: '보통',
    indoor: true,
    soloFriendly: true,
    timePerWeek: '보통',
    starterGuide: '아두이노 스타터 키트를 구매하세요. LED 깜빡이기부터 시작합니다.',
    categories: ['mind-indoor', 'indoor-mind', 'focus-logic'],
  },
];
