export interface Destination {
  id: string;
  name: string;
  country: string;
  region: 'domestic' | 'asia' | 'europe' | 'americas' | 'oceania';
  description: string;
  bestSeasons: string[];
  budgetLevel: 'low' | 'medium' | 'high';
  recommendedDays: number[];
  travelStyles: string[];
  companions: string[];
  highlights: string[];
  activities: string[];
  foods: string[];
  tips: string[];
  pros: string[];
  cons: string[];
  estimatedBudget: {
    flight: string;
    accommodation: string;
    daily: string;
  };
  mustVisit: string[];
  transportation: string;
  language: string;
  timezone: string;
}

export const destinations: Destination[] = [
  // 국내 여행지
  {
    id: 'jeju',
    name: '제주도',
    country: '한국',
    region: 'domestic',
    description: '한국의 대표 힐링 여행지. 아름다운 자연과 독특한 문화가 공존하는 섬',
    bestSeasons: ['봄', '가을'],
    budgetLevel: 'medium',
    recommendedDays: [2, 3, 4],
    travelStyles: ['휴양', '자연', '미식', '드라이브'],
    companions: ['커플', '가족', '친구', '혼자'],
    highlights: ['한라산', '성산일출봉', '우도', '섭지코지', '협재해수욕장', '카멜리아힐'],
    activities: ['올레길 걷기', '스노클링', '승마 체험', '카페 투어', '감귤 따기', '해녀 체험'],
    foods: ['흑돼지 구이', '갈치조림', '전복죽', '고등어회', '몸국', '한라봉'],
    tips: [
      '렌터카 예약은 최소 2주 전에',
      '성수기(7-8월, 연말연시) 피하면 가성비 좋음',
      '동쪽과 서쪽 날씨가 다를 수 있으니 일정 유연하게',
      '해안도로 드라이브 필수 코스',
    ],
    pros: ['국내 여행이라 편리함', '다양한 볼거리', '맛집 천국', '사계절 매력'],
    cons: ['성수기 물가 비쌈', '렌터카 필수', '바람 많음', '비행기값 변동 큼'],
    estimatedBudget: {
      flight: '10-30만원 (왕복)',
      accommodation: '5-15만원/박',
      daily: '5-10만원',
    },
    mustVisit: ['한라산 백록담', '성산일출봉', '만장굴', '협재해수욕장'],
    transportation: '렌터카 필수',
    language: '한국어',
    timezone: 'KST (UTC+9)',
  },
  {
    id: 'busan',
    name: '부산',
    country: '한국',
    region: 'domestic',
    description: '한국 제2의 도시. 바다와 도시가 어우러진 항구 도시',
    bestSeasons: ['여름', '가을'],
    budgetLevel: 'low',
    recommendedDays: [2, 3],
    travelStyles: ['관광', '미식', '액티비티', '문화'],
    companions: ['커플', '가족', '친구', '혼자'],
    highlights: ['해운대', '광안리', '감천문화마을', '태종대', '자갈치시장', '송도해수욕장'],
    activities: ['해변 산책', '야경 감상', '시장 투어', '케이블카 타기', '서핑', '온천'],
    foods: ['밀면', '돼지국밥', '회', '씨앗호떡', '아귀찜', '동래파전'],
    tips: [
      'KTX로 2시간 30분이면 도착',
      '지하철과 버스로 대부분 이동 가능',
      '자갈치시장 새벽 경매 구경 추천',
      '광안대교 야경은 필수',
    ],
    pros: ['교통 편리', '맛집 많음', '볼거리 다양', '저렴한 물가'],
    cons: ['여름 매우 더움', '관광지 혼잡', '주차 어려움'],
    estimatedBudget: {
      flight: 'KTX 6만원 (왕복)',
      accommodation: '4-10만원/박',
      daily: '3-7만원',
    },
    mustVisit: ['감천문화마을', '해운대', '광안리', '자갈치시장'],
    transportation: '대중교통 편리',
    language: '한국어',
    timezone: 'KST (UTC+9)',
  },
  {
    id: 'gangneung',
    name: '강릉',
    country: '한국',
    region: 'domestic',
    description: '동해안의 보석. 커피와 바다의 도시',
    bestSeasons: ['여름', '가을'],
    budgetLevel: 'low',
    recommendedDays: [1, 2, 3],
    travelStyles: ['휴양', '자연', '미식', '카페'],
    companions: ['커플', '친구', '혼자'],
    highlights: ['경포대', '안목해변', '정동진', '주문진', '오죽헌', '강문해변'],
    activities: ['카페 투어', '해변 산책', '일출 보기', '자전거 라이딩', '해수욕'],
    foods: ['물회', '초당순두부', '감자옹심이', '명란', '오징어순대', '커피'],
    tips: [
      'KTX로 서울에서 2시간',
      '안목해변 커피거리 필수 코스',
      '정동진 일출 감상 추천',
      '렌터카 있으면 편리',
    ],
    pros: ['접근성 좋음', '카페 문화', '깨끗한 해변', '한적함'],
    cons: ['겨울 매우 추움', '볼거리 제한적', '대중교통 불편'],
    estimatedBudget: {
      flight: 'KTX 4만원 (왕복)',
      accommodation: '5-12만원/박',
      daily: '4-8만원',
    },
    mustVisit: ['안목해변 커피거리', '경포대', '정동진', '주문진해변'],
    transportation: '렌터카 추천',
    language: '한국어',
    timezone: 'KST (UTC+9)',
  },
  {
    id: 'gyeongju',
    name: '경주',
    country: '한국',
    region: 'domestic',
    description: '지붕 없는 박물관. 신라 천년의 역사가 살아있는 도시',
    bestSeasons: ['봄', '가을'],
    budgetLevel: 'low',
    recommendedDays: [1, 2],
    travelStyles: ['문화', '관광', '역사'],
    companions: ['가족', '친구', '커플'],
    highlights: ['불국사', '석굴암', '첨성대', '동궁과월지', '대릉원', '양동마을'],
    activities: ['문화재 관람', '한복 체험', '자전거 투어', '박물관 견학'],
    foods: ['황남빵', '경주빵', '쌈밥', '한정식', '찰보리빵'],
    tips: [
      'KTX로 서울에서 2시간',
      '문화재 관람은 오전 일찍 시작',
      '자전거로 도시 투어 추천',
      '경주월드 놀이공원도 있음',
    ],
    pros: ['역사 교육', '저렴한 물가', '볼거리 집중', '교통 편리'],
    cons: ['식당 선택 제한적', '현대적 편의시설 부족', '여름 더움'],
    estimatedBudget: {
      flight: 'KTX 5만원 (왕복)',
      accommodation: '4-9만원/박',
      daily: '3-6만원',
    },
    mustVisit: ['불국사', '석굴암', '첨성대', '동궁과월지'],
    transportation: '자전거/택시',
    language: '한국어',
    timezone: 'KST (UTC+9)',
  },
  {
    id: 'jeonju',
    name: '전주',
    country: '한국',
    region: 'domestic',
    description: '한국의 맛과 멋이 살아있는 전통의 도시',
    bestSeasons: ['봄', '가을'],
    budgetLevel: 'low',
    recommendedDays: [1, 2],
    travelStyles: ['미식', '문화', '관광'],
    companions: ['커플', '친구', '가족'],
    highlights: ['한옥마을', '풍남문', '경기전', '오목대', '전동성당'],
    activities: ['한복 체험', '맛집 투어', '전통시장 구경', '야시장'],
    foods: ['비빔밥', '콩나물국밥', '막걸리', '초코파이', '한정식', '가맥'],
    tips: [
      'KTX로 서울에서 1시간 40분',
      '한옥마을 야경 필수',
      '남부시장 청년몰 추천',
      '주말 매우 혼잡',
    ],
    pros: ['맛집 천국', '한옥 체험', '접근성', '저렴한 물가'],
    cons: ['주말 인파', '주차 어려움', '볼거리 집중'],
    estimatedBudget: {
      flight: 'KTX 4만원 (왕복)',
      accommodation: '5-10만원/박',
      daily: '3-7만원',
    },
    mustVisit: ['한옥마을', '남부시장', '경기전', '전동성당'],
    transportation: '대중교통/도보',
    language: '한국어',
    timezone: 'KST (UTC+9)',
  },

  // 일본
  {
    id: 'tokyo',
    name: '도쿄',
    country: '일본',
    region: 'asia',
    description: '현대와 전통이 공존하는 일본의 수도. 무한한 가능성의 도시',
    bestSeasons: ['봄', '가을'],
    budgetLevel: 'high',
    recommendedDays: [3, 4, 5],
    travelStyles: ['관광', '쇼핑', '미식', '문화'],
    companions: ['커플', '친구', '혼자'],
    highlights: ['도쿄타워', '시부야', '아사쿠사', '하라주쿠', '오다이바', '디즈니랜드'],
    activities: ['쇼핑', '미술관 관람', '라멘 투어', '야경 감상', '온천', '디즈니'],
    foods: ['스시', '라멘', '덴푸라', '야끼토리', '오코노미야키', '회전초밥'],
    tips: [
      'JR패스 구매 시 지방 여행 계획',
      '시부야-신주쿠-하라주쿠는 한 라인',
      '편의점 음식도 수준급',
      '지하철 노선도 미리 공부',
    ],
    pros: ['대중교통 편리', '다양한 볼거리', '안전', '깨끗함'],
    cons: ['물가 비쌈', '영어 소통 어려움', '복잡함', '숙박비 높음'],
    estimatedBudget: {
      flight: '20-60만원 (왕복)',
      accommodation: '8-20만원/박',
      daily: '10-15만원',
    },
    mustVisit: ['아사쿠사 센소지', '시부야 스크램블', '메이지신궁', '도쿄타워'],
    transportation: 'JR패스/지하철',
    language: '일본어 (영어 제한적)',
    timezone: 'JST (UTC+9)',
  },
  {
    id: 'osaka',
    name: '오사카',
    country: '일본',
    region: 'asia',
    description: '일본의 부엌. 먹방 여행의 성지',
    bestSeasons: ['봄', '가을'],
    budgetLevel: 'medium',
    recommendedDays: [2, 3, 4],
    travelStyles: ['미식', '쇼핑', '관광', '문화'],
    companions: ['커플', '친구', '가족'],
    highlights: ['도톤보리', '오사카성', 'USJ', '신사이바시', '쿠로몬시장', '덴포잔'],
    activities: ['먹방 투어', 'USJ', '쇼핑', '야경 감상', '온천'],
    foods: ['타코야키', '오코노미야키', '쿠시카츠', '이카야키', '라멘', '회'],
    tips: [
      '도쿄보다 물가 저렴',
      '교토/나라 당일치기 가능',
      '도톤보리 야경 필수',
      'USJ는 평일 추천',
    ],
    pros: ['맛집 천국', '활기찬 분위기', '친근한 사람들', '교통 편리'],
    cons: ['복잡함', '시끄러움', '여름 더움'],
    estimatedBudget: {
      flight: '20-50만원 (왕복)',
      accommodation: '7-15만원/박',
      daily: '8-12만원',
    },
    mustVisit: ['도톤보리', '오사카성', 'USJ', '쿠로몬시장'],
    transportation: '지하철/도보',
    language: '일본어 (영어 제한적)',
    timezone: 'JST (UTC+9)',
  },
  {
    id: 'fukuoka',
    name: '후쿠오카',
    country: '일본',
    region: 'asia',
    description: '일본에서 가장 가까운 도시. 부산에서 2시간 30분',
    bestSeasons: ['봄', '가을'],
    budgetLevel: 'medium',
    recommendedDays: [2, 3],
    travelStyles: ['미식', '쇼핑', '휴양'],
    companions: ['커플', '친구', '혼자'],
    highlights: ['하카타', '텐진', '캐널시티', '오호리공원', '다자이후', '야타이'],
    activities: ['야타이 투어', '쇼핑', '온천', '라멘 순례', '신사 관람'],
    foods: ['하카타 라멘', '모츠나베', '멘타이코', '우동', '야끼토리'],
    tips: [
      '부산에서 배로 입국 가능',
      '야타이는 저녁 7시 이후',
      '텐진-하카타 지하철로 10분',
      '다자이후 당일치기 추천',
    ],
    pros: ['접근성 최고', '맛집 많음', '컴팩트한 도시', '친절함'],
    cons: ['볼거리 제한적', '날씨 변덕', '영어 소통 어려움'],
    estimatedBudget: {
      flight: '15-40만원 (왕복)',
      accommodation: '6-12만원/박',
      daily: '7-10만원',
    },
    mustVisit: ['야타이 거리', '다자이후텐만구', '오호리공원', '캐널시티'],
    transportation: '지하철/도보',
    language: '일본어',
    timezone: 'JST (UTC+9)',
  },
  {
    id: 'kyoto',
    name: '교토',
    country: '일본',
    region: 'asia',
    description: '천년 고도. 일본 전통문화의 심장',
    bestSeasons: ['봄', '가을'],
    budgetLevel: 'medium',
    recommendedDays: [2, 3],
    travelStyles: ['문화', '관광', '역사'],
    companions: ['커플', '친구', '혼자'],
    highlights: ['금각사', '은각사', '후시미이나리', '기온', '아라시야마', '청수사'],
    activities: ['신사 관람', '한복 체험', '차 체험', '대나무숲 산책', '정원 감상'],
    foods: ['카이세키', '유도후', '교토 라멘', '말차 디저트', '오바ン자이'],
    tips: [
      '오사카에서 1시간',
      '아침 일찍 관광 추천',
      '버스 1일권 구매',
      '벚꽃/단풍 시즌 예약 필수',
    ],
    pros: ['전통 문화', '아름다운 경관', '조용함', '포토존 많음'],
    cons: ['물가 비쌈', '관광객 많음', '교통 불편', '영어 소통 어려움'],
    estimatedBudget: {
      flight: '20-50만원 (왕복)',
      accommodation: '8-18만원/박',
      daily: '8-12만원',
    },
    mustVisit: ['금각사', '후시미이나리', '아라시야마 대나무숲', '기온'],
    transportation: '버스/택시',
    language: '일본어',
    timezone: 'JST (UTC+9)',
  },

  // 동남아시아
  {
    id: 'bangkok',
    name: '방콕',
    country: '태국',
    region: 'asia',
    description: '천사의 도시. 화려한 사원과 활기찬 야시장',
    bestSeasons: ['겨울 (11-2월)'],
    budgetLevel: 'low',
    recommendedDays: [3, 4, 5],
    travelStyles: ['관광', '쇼핑', '미식', '문화'],
    companions: ['커플', '친구', '가족'],
    highlights: ['왓포', '왓아룬', '그랜드팰리스', '카오산로드', '짜뚜짝시장', '아시아티크'],
    activities: ['사원 관람', '태국 마사지', '야시장', '쇼핑', '루프탑 바', '수상시장'],
    foods: ['팟타이', '똠얌꿍', '망고스틱라이스', '쏨땀', '카오팟', '코코넛 아이스크림'],
    tips: [
      '그랩 택시 필수 앱',
      '사원 방문 시 복장 주의',
      '길거리 음식 안전',
      '더위 대비 필수',
    ],
    pros: ['저렴한 물가', '맛집 천국', '쇼핑 천국', '친절함'],
    cons: ['매우 더움', '교통 체증', '습함', '공해'],
    estimatedBudget: {
      flight: '30-80만원 (왕복)',
      accommodation: '3-10만원/박',
      daily: '3-7만원',
    },
    mustVisit: ['그랜드팰리스', '왓포', '짜뚜짝시장', '카오산로드'],
    transportation: 'BTS/MRT/그랩',
    language: '태국어 (영어 가능)',
    timezone: 'ICT (UTC+7)',
  },
  {
    id: 'danang',
    name: '다낭',
    country: '베트남',
    region: 'asia',
    description: '베트남의 떠오르는 휴양도시. 깨끗한 해변과 합리적인 가격',
    bestSeasons: ['여름 (5-8월)'],
    budgetLevel: 'low',
    recommendedDays: [3, 4, 5],
    travelStyles: ['휴양', '관광', '미식'],
    companions: ['커플', '가족', '친구'],
    highlights: ['미케비치', '바나힐', '오행산', '한시장', '용다리', '호이안'],
    activities: ['해수욕', '바나힐', '쇼핑', '마사지', '호이안 투어', '해산물'],
    foods: ['반미', '분짜', '꼬마', '반쎄오', '해산물', '망고빙수'],
    tips: [
      '호이안 당일치기 필수',
      '바나힐은 오전 일찍',
      '그랩 택시 저렴',
      '해산물 거리 저녁 추천',
    ],
    pros: ['가성비 최고', '깨끗한 해변', '맛집 많음', '치안 좋음'],
    cons: ['더움', '영어 소통 제한적', '택시 바가지', '비오는 날 많음'],
    estimatedBudget: {
      flight: '20-60만원 (왕복)',
      accommodation: '3-8만원/박',
      daily: '3-6만원',
    },
    mustVisit: ['바나힐', '호이안 고대도시', '미케비치', '한시장'],
    transportation: '그랩/택시',
    language: '베트남어 (영어 제한적)',
    timezone: 'ICT (UTC+7)',
  },
  {
    id: 'phuket',
    name: '푸켓',
    country: '태국',
    region: 'asia',
    description: '태국 최대의 섬. 에메랄드 바다와 야시장',
    bestSeasons: ['겨울 (11-3월)'],
    budgetLevel: 'medium',
    recommendedDays: [4, 5, 6],
    travelStyles: ['휴양', '액티비티', '미식'],
    companions: ['커플', '친구', '가족'],
    highlights: ['파통비치', '카론비치', '빅부다', '프롬텝곶', '올드타운', '피피섬'],
    activities: ['스노클링', '다이빙', '코끼리 트래킹', '섬 투어', '마사지', '야시장'],
    foods: ['팟타이', '똠얌꿍', '해산물 BBQ', '망고스틱라이스', '쏨땀'],
    tips: [
      '피피섬 투어 필수',
      '파통비치는 밤 문화',
      '카론비치는 조용함',
      '그랩 택시 편리',
    ],
    pros: ['아름다운 해변', '다양한 액티비티', '나이트라이프', '맛집'],
    cons: ['비싼 편', '관광객 많음', '우기 피해야 함', '이동 거리'],
    estimatedBudget: {
      flight: '40-100만원 (왕복)',
      accommodation: '5-15만원/박',
      daily: '5-10만원',
    },
    mustVisit: ['피피섬', '빅부다', '파통비치', '올드타운'],
    transportation: '그랩/렌터카',
    language: '태국어 (영어 가능)',
    timezone: 'ICT (UTC+7)',
  },
  {
    id: 'singapore',
    name: '싱가포르',
    country: '싱가포르',
    region: 'asia',
    description: '도시국가의 완벽함. 깨끗하고 안전한 미래도시',
    bestSeasons: ['연중 (건기 2-4월)'],
    budgetLevel: 'high',
    recommendedDays: [3, 4],
    travelStyles: ['관광', '쇼핑', '미식', '가족'],
    companions: ['가족', '커플', '친구'],
    highlights: ['마리나베이샌즈', '가든스바이더베이', '센토사', '오차드로드', '차이나타운', 'USS'],
    activities: ['쇼핑', 'USS', '야경 감상', '호커센터', '동물원', '야간 사파리'],
    foods: ['칠리크랩', '치킨라이스', '락사', '바쿠테', '카야토스트', '호커센터'],
    tips: [
      '대중교통 완벽',
      'MBS 루프탑 예약 필수',
      '호커센터 저렴',
      '껌/담배 규제 주의',
    ],
    pros: ['깨끗함', '안전', '대중교통 편리', '영어 소통', '다양한 음식'],
    cons: ['물가 비쌈', '더움', '볼거리 제한적', '작은 나라'],
    estimatedBudget: {
      flight: '30-80만원 (왕복)',
      accommodation: '10-25만원/박',
      daily: '10-15만원',
    },
    mustVisit: ['마리나베이샌즈', '가든스바이더베이', 'USS', '나이트 사파리'],
    transportation: 'MRT/버스',
    language: '영어/중국어/말레이어',
    timezone: 'SGT (UTC+8)',
  },

  // 유럽
  {
    id: 'paris',
    name: '파리',
    country: '프랑스',
    region: 'europe',
    description: '빛의 도시. 예술과 낭만의 수도',
    bestSeasons: ['봄', '가을'],
    budgetLevel: 'high',
    recommendedDays: [4, 5, 6],
    travelStyles: ['문화', '관광', '미식', '쇼핑'],
    companions: ['커플', '친구', '혼자'],
    highlights: ['에펠탑', '루브르', '개선문', '노트르담', '샹젤리제', '몽마르뜨'],
    activities: ['미술관 관람', '세느강 유람', '카페 투어', '쇼핑', '야경 감상'],
    foods: ['크루아상', '에스카르고', '스테이크', '와인', '마카롱', '치즈'],
    tips: [
      '박물관 패스 구매',
      '소매치기 주의',
      '메트로 24시간권 추천',
      '레스토랑 예약 필수',
    ],
    pros: ['예술의 도시', '아름다운 건축', '맛집', '패션'],
    cons: ['물가 매우 비쌈', '치안 주의', '영어 소통 제한적', '복잡함'],
    estimatedBudget: {
      flight: '80-200만원 (왕복)',
      accommodation: '15-40만원/박',
      daily: '15-25만원',
    },
    mustVisit: ['에펠탑', '루브르박물관', '개선문', '베르사유궁전'],
    transportation: '메트로/도보',
    language: '프랑스어 (영어 제한적)',
    timezone: 'CET (UTC+1)',
  },
  {
    id: 'london',
    name: '런던',
    country: '영국',
    region: 'europe',
    description: '영국의 심장. 전통과 현대가 공존하는 도시',
    bestSeasons: ['여름 (6-8월)'],
    budgetLevel: 'high',
    recommendedDays: [4, 5, 6],
    travelStyles: ['문화', '관광', '쇼핑'],
    companions: ['커플', '친구', '가족'],
    highlights: ['빅벤', '버킹엄궁전', '대영박물관', '타워브릿지', '하이드파크', '템즈강'],
    activities: ['박물관 투어', '뮤지컬 관람', '애프터눈티', '쇼핑', '펍 투어'],
    foods: ['피쉬앤칩스', '로스트비프', '애프터눈티', '파이', '인도커리'],
    tips: [
      '오이스터카드 필수',
      '박물관 대부분 무료',
      '뮤지컬 예매 추천',
      '우산 필수',
    ],
    pros: ['영어 소통', '무료 박물관', '대중교통 편리', '다양한 문화'],
    cons: ['물가 매우 비쌈', '날씨 변덕', '음식 평가 낮음', '복잡함'],
    estimatedBudget: {
      flight: '100-250만원 (왕복)',
      accommodation: '20-50만원/박',
      daily: '15-30만원',
    },
    mustVisit: ['대영박물관', '버킹엄궁전', '빅벤', '타워브릿지'],
    transportation: '튜브/버스',
    language: '영어',
    timezone: 'GMT (UTC+0)',
  },
  {
    id: 'barcelona',
    name: '바르셀로나',
    country: '스페인',
    region: 'europe',
    description: '가우디의 도시. 지중해의 예술 도시',
    bestSeasons: ['봄', '가을'],
    budgetLevel: 'medium',
    recommendedDays: [3, 4, 5],
    travelStyles: ['문화', '관광', '미식', '휴양'],
    companions: ['커플', '친구', '가족'],
    highlights: ['사그라다파밀리아', '구엘공원', '람블라스거리', '고딕지구', '바르셀로네타'],
    activities: ['가우디 건축 투어', '해변', '타파스 투어', '축구 경기', '산책'],
    foods: ['타파스', '파에야', '하몽', '상그리아', '츄로스'],
    tips: [
      '사그라다파밀리아 예약 필수',
      '소매치기 극심 주의',
      '시에스타 시간 체크',
      '타파스는 저녁 늦게',
    ],
    pros: ['아름다운 건축', '맛집', '해변', '활기찬 분위기'],
    cons: ['소매치기', '관광객 많음', '영어 소통 제한적'],
    estimatedBudget: {
      flight: '80-180만원 (왕복)',
      accommodation: '10-30만원/박',
      daily: '10-20만원',
    },
    mustVisit: ['사그라다파밀리아', '구엘공원', '람블라스거리', '까사바트요'],
    transportation: '메트로/도보',
    language: '스페인어/카탈루냐어',
    timezone: 'CET (UTC+1)',
  },

  // 기타 인기 여행지
  {
    id: 'newyork',
    name: '뉴욕',
    country: '미국',
    region: 'americas',
    description: '잠들지 않는 도시. 세계의 중심',
    bestSeasons: ['봄', '가을'],
    budgetLevel: 'high',
    recommendedDays: [5, 6, 7],
    travelStyles: ['문화', '관광', '쇼핑', '미식'],
    companions: ['커플', '친구', '혼자'],
    highlights: ['자유의여신상', '타임스퀘어', '센트럴파크', '브루클린브릿지', '엠파이어스테이트'],
    activities: ['박물관 투어', '뮤지컬 관람', '쇼핑', '루프탑 바', '공원 산책'],
    foods: ['뉴욕피자', '핫도그', '베이글', '스테이크', '치즈케이크'],
    tips: [
      '메트로카드 구매',
      '뮤지컬 TKTS 반값',
      '팁 문화 필수',
      'ESTA 신청',
    ],
    pros: ['다양한 문화', '볼거리 무한', '대중교통', '24시간 활기'],
    cons: ['물가 최상', '복잡함', '치안 주의', '피곤함'],
    estimatedBudget: {
      flight: '100-300만원 (왕복)',
      accommodation: '20-60만원/박',
      daily: '20-40만원',
    },
    mustVisit: ['자유의여신상', '타임스퀘어', '센트럴파크', '브루클린브릿지'],
    transportation: '지하철/도보',
    language: '영어',
    timezone: 'EST (UTC-5)',
  },
  {
    id: 'sydney',
    name: '시드니',
    country: '호주',
    region: 'oceania',
    description: '남반구의 보석. 아름다운 항구도시',
    bestSeasons: ['봄 (9-11월)', '가을 (3-5월)'],
    budgetLevel: 'high',
    recommendedDays: [4, 5, 6],
    travelStyles: ['관광', '휴양', '액티비티'],
    companions: ['커플', '친구', '가족'],
    highlights: ['오페라하우스', '하버브릿지', '본다이비치', '달링하버', '블루마운틴'],
    activities: ['서핑', '하버 크루즈', '브릿지 클라임', '동물원', '해변 산책'],
    foods: ['피쉬앤칩스', 'BBQ', '미트파이', '플랫화이트', '캥거루고기'],
    tips: [
      '시차 적응 필요',
      '오팔카드 필수',
      '블루마운틴 당일치기',
      '해변 안전 주의',
    ],
    pros: ['깨끗함', '안전', '영어 소통', '아름다운 자연'],
    cons: ['물가 매우 비쌈', '비행 시간 김', '시차', '멀음'],
    estimatedBudget: {
      flight: '100-250만원 (왕복)',
      accommodation: '15-40만원/박',
      daily: '15-30만원',
    },
    mustVisit: ['오페라하우스', '하버브릿지', '본다이비치', '블루마운틴'],
    transportation: '대중교통/페리',
    language: '영어',
    timezone: 'AEDT (UTC+11)',
  },
];

export function getDestinationsByFilters(filters: {
  travelStyle?: string;
  budget?: string;
  days?: number;
  companions?: string;
  region?: string;
}): Destination[] {
  let filtered = [...destinations];

  if (filters.region && filters.region !== 'all') {
    filtered = filtered.filter((d) => d.region === filters.region);
  }

  if (filters.travelStyle) {
    filtered = filtered.filter((d) => d.travelStyles.includes(filters.travelStyle!));
  }

  if (filters.budget) {
    filtered = filtered.filter((d) => d.budgetLevel === filters.budget);
  }

  if (filters.days) {
    filtered = filtered.filter((d) => d.recommendedDays.includes(filters.days!));
  }

  if (filters.companions) {
    filtered = filtered.filter((d) => d.companions.includes(filters.companions!));
  }

  return filtered;
}
