export interface Vitamin {
  id: string;
  name: string;
  scientificName: string;
  emoji: string;
  category: 'fat-soluble' | 'water-soluble' | 'mineral' | 'other';
  description: string;
  functions: string[];
  deficiencySymptoms: string[];
  excessSymptoms: string[];
  foodSources: string[];
  recommendedDailyIntake: {
    men: string;
    women: string;
  };
  benefits: string[];
  bestTakenWith: string[];
  warnings: string[];
  whoNeedsIt: string[];
}

export const vitamins: Vitamin[] = [
  {
    id: 'vitamin-a',
    name: '비타민 A',
    scientificName: 'Retinol',
    emoji: '👁️',
    category: 'fat-soluble',
    description: '시력 건강과 면역력 증진에 필수적인 지용성 비타민',
    functions: ['시력 유지', '면역 기능 강화', '피부 건강', '세포 성장 및 분화', '항산화 작용'],
    deficiencySymptoms: [
      '야맹증',
      '안구 건조증',
      '피부 건조 및 각질',
      '면역력 저하',
      '성장 지연',
      '시력 저하',
    ],
    excessSymptoms: ['두통', '어지러움', '피부 벗겨짐', '간 손상', '뼈 약화'],
    foodSources: ['당근', '고구마', '시금치', '브로콜리', '간', '우유', '계란 노른자', '망고'],
    recommendedDailyIntake: {
      men: '900 mcg',
      women: '700 mcg',
    },
    benefits: [
      '눈 건강 개선 (특히 야간 시력)',
      '면역 체계 강화',
      '여드름 및 피부 문제 개선',
      '항암 효과',
    ],
    bestTakenWith: ['지방이 포함된 음식', '비타민 D', '비타민 E'],
    warnings: [
      '임신 초기 과다 섭취 주의',
      '흡연자는 베타카로틴 보충제 피하기',
      '지용성이라 과다 섭취 시 체내 축적',
    ],
    whoNeedsIt: ['야맹증이 있는 사람', '피부가 건조한 사람', '면역력이 약한 사람', '채식주의자'],
  },
  {
    id: 'vitamin-b1',
    name: '비타민 B1',
    scientificName: 'Thiamine',
    emoji: '⚡',
    category: 'water-soluble',
    description: '에너지 대사와 신경계 건강에 필수적인 수용성 비타민',
    functions: ['탄수화물 대사', '신경 기능 유지', '에너지 생성', '근육 기능', '심장 건강'],
    deficiencySymptoms: [
      '만성 피로',
      '식욕 부진',
      '체중 감소',
      '기억력 감퇴',
      '다리 저림',
      '근육 약화',
      '각기병',
    ],
    excessSymptoms: ['매우 드묾 (수용성이라 과잉 배출)'],
    foodSources: ['돼지고기', '현미', '통곡물', '콩류', '견과류', '해바라기씨', '귀리'],
    recommendedDailyIntake: {
      men: '1.2 mg',
      women: '1.1 mg',
    },
    benefits: ['에너지 생성 촉진', '신경 건강', '심장 기능 개선', '소화 기능 향상'],
    bestTakenWith: ['다른 B 비타민군', '마그네슘'],
    warnings: ['알코올 섭취 시 흡수 저하', '커피/차와 함께 섭취 피하기'],
    whoNeedsIt: ['피로가 심한 사람', '술을 자주 마시는 사람', '탄수화물 섭취가 많은 사람'],
  },
  {
    id: 'vitamin-b2',
    name: '비타민 B2',
    scientificName: 'Riboflavin',
    emoji: '💡',
    category: 'water-soluble',
    description: '세포 에너지 생산과 항산화 작용에 중요한 비타민',
    functions: ['에너지 대사', '항산화 작용', '피부/눈/신경 건강', '세포 성장', '철분 흡수'],
    deficiencySymptoms: ['입술/입 안 염증', '혀의 붉은 반점', '눈 충혈', '피부 갈라짐', '빈혈'],
    excessSymptoms: ['소변 색 변화 (노란색)', '극히 드물게 설사'],
    foodSources: ['우유', '요거트', '치즈', '계란', '간', '연어', '시금치', '버섯'],
    recommendedDailyIntake: {
      men: '1.3 mg',
      women: '1.1 mg',
    },
    benefits: ['편두통 예방', '눈 건강', '피부 재생', '에너지 생산'],
    bestTakenWith: ['다른 B 비타민', '비타민 A'],
    warnings: ['빛에 민감하므로 어두운 곳 보관'],
    whoNeedsIt: ['편두통이 있는 사람', '운동을 많이 하는 사람', '구내염이 잦은 사람'],
  },
  {
    id: 'vitamin-b3',
    name: '비타민 B3',
    scientificName: 'Niacin',
    emoji: '❤️',
    category: 'water-soluble',
    description: '콜레스테롤 관리와 에너지 대사에 핵심적인 비타민',
    functions: ['에너지 생성', '콜레스테롤 조절', 'DNA 복구', '호르몬 합성', '신경 기능'],
    deficiencySymptoms: ['피부 염증', '설사', '치매', '우울증', '피로', '소화불량'],
    excessSymptoms: ['피부 홍조', '가려움', '간 손상 (고용량 시)', '혈당 상승'],
    foodSources: ['닭고기', '참치', '연어', '땅콩', '버섯', '아보카도', '현미'],
    recommendedDailyIntake: {
      men: '16 mg',
      women: '14 mg',
    },
    benefits: ['콜레스테롤 개선 (HDL 증가)', '심혈관 건강', '뇌 기능 향상', '피부 건강'],
    bestTakenWith: ['식사와 함께 (홍조 완화)', '비타민 B군'],
    warnings: ['당뇨병 환자 주의', '간 질환자 의사 상담', '고용량 섭취 시 홍조 발생'],
    whoNeedsIt: ['콜레스테롤이 높은 사람', '피부 트러블이 있는 사람', '우울증이 있는 사람'],
  },
  {
    id: 'vitamin-b6',
    name: '비타민 B6',
    scientificName: 'Pyridoxine',
    emoji: '🧠',
    category: 'water-soluble',
    description: '신경전달물질 합성과 단백질 대사에 필수적',
    functions: [
      '신경전달물질 합성',
      '단백질 대사',
      '헤모글로빈 생성',
      '면역 기능',
      '호르몬 조절',
    ],
    deficiencySymptoms: ['우울증', '혼란', '빈혈', '피부 염증', '면역력 저하', '경련'],
    excessSymptoms: ['신경 손상', '감각 이상', '피부 병변'],
    foodSources: ['닭고기', '생선', '감자', '바나나', '병아리콩', '현미', '견과류'],
    recommendedDailyIntake: {
      men: '1.3 mg',
      women: '1.3 mg',
    },
    benefits: ['우울증 완화', 'PMS 증상 개선', '입덧 완화', '면역력 강화', '뇌 기능 향상'],
    bestTakenWith: ['마그네슘', '다른 B 비타민', '아연'],
    warnings: ['장기간 고용량 섭취 시 신경 손상', '일부 약물과 상호작용'],
    whoNeedsIt: ['우울증이 있는 사람', '임산부', '생리전 증후군이 있는 여성', '빈혈이 있는 사람'],
  },
  {
    id: 'vitamin-b9',
    name: '비타민 B9 (엽산)',
    scientificName: 'Folate/Folic Acid',
    emoji: '🤰',
    category: 'water-soluble',
    description: '임신과 세포 분열에 매우 중요한 비타민',
    functions: ['DNA 합성', '세포 분열', '적혈구 생성', '태아 발달', '호모시스테인 조절'],
    deficiencySymptoms: ['빈혈', '피로', '입 안 궤양', '회백색 머리카락', '성장 지연', '태아 신경관 결손'],
    excessSymptoms: ['비타민 B12 결핍 은폐', '수면 장애', '소화 불량'],
    foodSources: ['시금치', '브로콜리', '아스파라거스', '콩류', '렌틸콩', '아보카도', '오렌지'],
    recommendedDailyIntake: {
      men: '400 mcg',
      women: '400 mcg (임신 시 600 mcg)',
    },
    benefits: [
      '태아 신경관 결손 예방',
      '심혈관 질환 예방',
      '우울증 개선',
      '암 예방 (일부 연구)',
    ],
    bestTakenWith: ['비타민 B12', '비타민 C', '아연'],
    warnings: ['임신 계획 시 미리 복용', '과다 섭취 시 B12 결핍 은폐'],
    whoNeedsIt: ['임신 계획 중인 여성', '임산부', '빈혈이 있는 사람', '알코올 섭취가 많은 사람'],
  },
  {
    id: 'vitamin-b12',
    name: '비타민 B12',
    scientificName: 'Cobalamin',
    emoji: '🔋',
    category: 'water-soluble',
    description: '신경계와 적혈구 생성에 필수적인 비타민',
    functions: ['적혈구 생성', '신경 기능', 'DNA 합성', '에너지 대사', '뇌 건강'],
    deficiencySymptoms: [
      '극심한 피로',
      '빈혈',
      '손발 저림',
      '기억력 감퇴',
      '우울증',
      '균형 감각 상실',
      '혀 염증',
    ],
    excessSymptoms: ['드묾 (과잉 시 배출)'],
    foodSources: ['소고기', '간', '생선', '조개', '계란', '우유', '치즈', '강화 시리얼'],
    recommendedDailyIntake: {
      men: '2.4 mcg',
      women: '2.4 mcg',
    },
    benefits: ['빈혈 예방', '에너지 증진', '뇌 기능 향상', '기분 개선', '심혈관 건강'],
    bestTakenWith: ['엽산', '칼슘', '다른 B 비타민'],
    warnings: ['채식주의자 필수 보충', '흡수 장애가 있는 노인 주의'],
    whoNeedsIt: [
      '채식주의자/비건',
      '노인',
      '피로가 심한 사람',
      '빈혈이 있는 사람',
      '위장 수술을 받은 사람',
    ],
  },
  {
    id: 'vitamin-c',
    name: '비타민 C',
    scientificName: 'Ascorbic Acid',
    emoji: '🍊',
    category: 'water-soluble',
    description: '강력한 항산화제이자 면역력 증진 비타민',
    functions: ['항산화 작용', '콜라겐 합성', '면역 기능', '철분 흡수', '상처 치유'],
    deficiencySymptoms: [
      '잇몸 출혈',
      '쉽게 멍듦',
      '상처 회복 느림',
      '피로',
      '피부 건조',
      '괴혈병 (극단적)',
    ],
    excessSymptoms: ['설사', '복통', '신장 결석 위험', '메스꺼움'],
    foodSources: ['오렌지', '딸기', '키위', '브로콜리', '파프리카', '토마토', '시금치'],
    recommendedDailyIntake: {
      men: '90 mg',
      women: '75 mg',
    },
    benefits: [
      '감기 예방 및 완화',
      '피부 노화 방지',
      '면역력 강화',
      '철분 흡수 촉진',
      '항산화 효과',
    ],
    bestTakenWith: ['철분', '비타민 E', '식사와 함께'],
    warnings: [
      '신장 결석 병력자 주의',
      '1일 2000mg 이상 피하기',
      '흡연자는 더 많이 필요',
    ],
    whoNeedsIt: ['면역력이 약한 사람', '흡연자', '스트레스가 많은 사람', '피부 노화가 걱정되는 사람'],
  },
  {
    id: 'vitamin-d',
    name: '비타민 D',
    scientificName: 'Calciferol',
    emoji: '☀️',
    category: 'fat-soluble',
    description: '뼈 건강과 면역력에 핵심적인 햇빛 비타민',
    functions: ['칼슘 흡수', '뼈 건강', '면역 기능', '근육 기능', '기분 조절'],
    deficiencySymptoms: [
      '뼈 통증',
      '근육 약화',
      '피로',
      '우울증',
      '면역력 저하',
      '골다공증',
      '구루병 (어린이)',
    ],
    excessSymptoms: ['고칼슘혈증', '메스꺼움', '변비', '신장 손상'],
    foodSources: ['연어', '고등어', '참치', '계란 노른자', '우유 (강화)', '버섯', '햇빛'],
    recommendedDailyIntake: {
      men: '600 IU (15 mcg)',
      women: '600 IU (15 mcg)',
    },
    benefits: [
      '뼈와 치아 건강',
      '면역력 강화',
      '우울증 예방',
      '암 예방 (일부 연구)',
      '당뇨병 위험 감소',
    ],
    bestTakenWith: ['칼슘', '마그네슘', '비타민 K2', '지방이 포함된 식사'],
    warnings: ['햇빛 노출 10-30분/일 권장', '실내 생활자 보충 필수', '과다 섭취 주의'],
    whoNeedsIt: [
      '실내 생활이 많은 사람',
      '노인',
      '골다공증 위험이 있는 사람',
      '우울증이 있는 사람',
      '피부가 어두운 사람',
    ],
  },
  {
    id: 'vitamin-e',
    name: '비타민 E',
    scientificName: 'Tocopherol',
    emoji: '💚',
    category: 'fat-soluble',
    description: '강력한 항산화제로 세포 보호에 중요',
    functions: ['항산화 작용', '세포막 보호', '면역 기능', '피부 건강', '혈액 순환'],
    deficiencySymptoms: [
      '근육 약화',
      '시력 문제',
      '면역력 저하',
      '신경 손상',
      '걷기 어려움',
      '빈혈',
    ],
    excessSymptoms: ['출혈 위험 증가', '피로', '메스꺼움', '두통'],
    foodSources: ['아몬드', '해바라기씨', '시금치', '브로콜리', '키위', '아보카도', '올리브오일'],
    recommendedDailyIntake: {
      men: '15 mg',
      women: '15 mg',
    },
    benefits: ['피부 노화 방지', '상처 치유', '심혈관 건강', '뇌 기능 보호', '면역력 강화'],
    bestTakenWith: ['비타민 C', '셀레늄', '지방이 포함된 음식'],
    warnings: ['혈액 응고 약물 복용자 주의', '수술 전 중단', '고용량 피하기'],
    whoNeedsIt: [
      '피부 노화가 걱정되는 사람',
      '심혈관 질환 위험이 있는 사람',
      '운동을 많이 하는 사람',
    ],
  },
  {
    id: 'vitamin-k',
    name: '비타민 K',
    scientificName: 'Phylloquinone',
    emoji: '🩸',
    category: 'fat-soluble',
    description: '혈액 응고와 뼈 건강에 필수적',
    functions: ['혈액 응고', '뼈 건강', '칼슘 조절', '심혈관 건강', '상처 치유'],
    deficiencySymptoms: ['쉽게 멍듦', '코피', '잇몸 출혈', '생리량 증가', '골절 위험'],
    excessSymptoms: ['드묾 (음식으로는 과다 섭취 어려움)'],
    foodSources: ['케일', '시금치', '브로콜리', '양배추', '파슬리', '아스파라거스', '청경채'],
    recommendedDailyIntake: {
      men: '120 mcg',
      women: '90 mcg',
    },
    benefits: ['혈액 응고 정상화', '골밀도 증가', '심장 건강', '상처 치유 촉진'],
    bestTakenWith: ['비타민 D', '칼슘', '지방이 포함된 음식'],
    warnings: ['혈액 희석제 복용자 일정량 유지', '항생제 장기 복용 시 보충'],
    whoNeedsIt: [
      '멍이 잘 드는 사람',
      '골다공증 위험이 있는 사람',
      '항생제를 장기 복용하는 사람',
    ],
  },
  {
    id: 'iron',
    name: '철분',
    scientificName: 'Iron',
    emoji: '🔴',
    category: 'mineral',
    description: '적혈구 생성과 산소 운반에 필수적인 미네랄',
    functions: ['헤모글로빈 생성', '산소 운반', '에너지 생산', '면역 기능', '뇌 발달'],
    deficiencySymptoms: [
      '극심한 피로',
      '창백한 피부',
      '숨 가쁨',
      '두통',
      '어지러움',
      '차가운 손발',
      '취약한 손톱',
    ],
    excessSymptoms: ['메스꺼움', '변비', '간 손상', '복통'],
    foodSources: ['적색육', '간', '조개', '시금치', '콩류', '두부', '견과류', '계란'],
    recommendedDailyIntake: {
      men: '8 mg',
      women: '18 mg (폐경 후 8 mg)',
    },
    benefits: ['빈혈 예방', '에너지 증진', '면역력 강화', '집중력 향상', '운동 능력 향상'],
    bestTakenWith: ['비타민 C (흡수 촉진)', '공복 시 (흡수율 높음)'],
    warnings: [
      '칼슘/커피/차와 함께 섭취 피하기 (흡수 저해)',
      '과다 섭취 주의',
      '남성과 폐경 여성은 보충제 신중',
    ],
    whoNeedsIt: [
      '생리를 하는 여성',
      '임산부',
      '채식주의자',
      '빈혈이 있는 사람',
      '운동선수',
    ],
  },
  {
    id: 'magnesium',
    name: '마그네슘',
    scientificName: 'Magnesium',
    emoji: '😴',
    category: 'mineral',
    description: '300가지 이상의 효소 반응에 관여하는 필수 미네랄',
    functions: ['근육 이완', '신경 전달', '에너지 생성', '뼈 건강', '혈압 조절', '혈당 조절'],
    deficiencySymptoms: [
      '근육 경련',
      '피로',
      '불면증',
      '두통',
      '불안',
      '변비',
      '부정맥',
      '눈 떨림',
    ],
    excessSymptoms: ['설사', '메스꺼움', '저혈압', '호흡 곤란'],
    foodSources: ['아몬드', '시금치', '아보카도', '다크 초콜릿', '바나나', '현미', '콩류'],
    recommendedDailyIntake: {
      men: '400-420 mg',
      women: '310-320 mg',
    },
    benefits: [
      '수면의 질 개선',
      '근육 경련 완화',
      '편두통 감소',
      '불안 완화',
      '혈압 조절',
      '당뇨병 예방',
    ],
    bestTakenWith: ['비타민 D', '칼슘 (비율 중요)', '비타민 B6', '저녁 시간 (수면 도움)'],
    warnings: ['신장 질환자 주의', '제산제/이뇨제 복용 시 보충', '설사 시 복용량 조절'],
    whoNeedsIt: [
      '불면증이 있는 사람',
      '근육 경련이 잦은 사람',
      '스트레스가 많은 사람',
      '편두통이 있는 사람',
      '운동을 많이 하는 사람',
    ],
  },
  {
    id: 'zinc',
    name: '아연',
    scientificName: 'Zinc',
    emoji: '🛡️',
    category: 'mineral',
    description: '면역 기능과 상처 치유에 핵심적인 미네랄',
    functions: ['면역 기능', '상처 치유', '단백질 합성', '미각/후각', 'DNA 합성', '세포 분열'],
    deficiencySymptoms: [
      '면역력 저하',
      '탈모',
      '미각/후각 상실',
      '상처 회복 느림',
      '피부 발진',
      '설사',
      '성장 지연',
    ],
    excessSymptoms: ['메스꺼움', '구토', '식욕 감퇴', '복통', '두통', '면역력 저하'],
    foodSources: ['굴', '쇠고기', '게', '치즈', '병아리콩', '캐슈넛', '계란', '닭고기'],
    recommendedDailyIntake: {
      men: '11 mg',
      women: '8 mg',
    },
    benefits: [
      '감기 기간 단축',
      '여드름 개선',
      '상처 치유 촉진',
      '면역력 강화',
      '남성 생식 건강',
      '항산화',
    ],
    bestTakenWith: ['식사와 함께 (속 쓰림 방지)', '비타민 A', '구리 (균형 유지)'],
    warnings: [
      '공복 섭취 시 메스꺼움',
      '장기간 고용량 피하기',
      '구리 흡수 방해 (균형 필요)',
    ],
    whoNeedsIt: [
      '면역력이 약한 사람',
      '여드름이 있는 사람',
      '탈모가 있는 사람',
      '채식주의자',
      '임산부',
    ],
  },
  {
    id: 'calcium',
    name: '칼슘',
    scientificName: 'Calcium',
    emoji: '🦴',
    category: 'mineral',
    description: '뼈와 치아 건강의 핵심 미네랄',
    functions: ['뼈/치아 형성', '근육 수축', '신경 전달', '혈액 응고', '심장 박동'],
    deficiencySymptoms: [
      '골다공증',
      '골절 위험',
      '근육 경련',
      '손발 저림',
      '치아 문제',
      '불안',
      '우울증',
    ],
    excessSymptoms: ['변비', '신장 결석', '칼슘 침착', '철분/아연 흡수 방해'],
    foodSources: ['우유', '요거트', '치즈', '두부', '아몬드', '브로콜리', '케일', '멸치'],
    recommendedDailyIntake: {
      men: '1000 mg',
      women: '1000 mg (폐경 후 1200 mg)',
    },
    benefits: ['골다공증 예방', '치아 건강', '근육 경련 완화', '혈압 조절', 'PMS 완화'],
    bestTakenWith: ['비타민 D (흡수 필수)', '마그네슘', '비타민 K2', '식사와 함께'],
    warnings: [
      '철분과 시간 간격 두기',
      '1회 500mg 이하 분할 섭취',
      '신장 결석 병력자 주의',
    ],
    whoNeedsIt: [
      '노인',
      '폐경기 여성',
      '유제품을 먹지 않는 사람',
      '골다공증 위험이 있는 사람',
    ],
  },
  {
    id: 'omega-3',
    name: '오메가-3',
    scientificName: 'Omega-3 Fatty Acids',
    emoji: '🐟',
    category: 'other',
    description: '심장과 뇌 건강에 필수적인 지방산',
    functions: ['심혈관 건강', '뇌 기능', '항염증', '눈 건강', '관절 건강', '기분 조절'],
    deficiencySymptoms: [
      '건조한 피부',
      '우울증',
      '기억력 감퇴',
      '심장 질환 위험',
      '관절통',
      '피로',
    ],
    excessSymptoms: ['출혈 위험', '소화불량', '트림', '비린내'],
    foodSources: ['연어', '고등어', '정어리', '호두', '치아씨드', '아마씨', '대구간유'],
    recommendedDailyIntake: {
      men: '1.6 g',
      women: '1.1 g',
    },
    benefits: [
      '심장 질환 예방',
      '뇌 기능 향상',
      '우울증/불안 완화',
      '염증 감소',
      'ADHD 증상 완화',
      '눈 건강',
    ],
    bestTakenWith: ['식사와 함께 (흡수율 향상)', '비타민 E'],
    warnings: [
      '혈액 희석제 복용자 주의',
      '수술 전 중단',
      '품질 좋은 제품 선택 (중금속 오염)',
    ],
    whoNeedsIt: [
      '생선을 먹지 않는 사람',
      '심혈관 질환 위험이 있는 사람',
      '우울증이 있는 사람',
      '관절염이 있는 사람',
    ],
  },
  {
    id: 'probiotics',
    name: '프로바이오틱스',
    scientificName: 'Probiotics',
    emoji: '🦠',
    category: 'other',
    description: '장 건강과 면역력에 도움을 주는 유익균',
    functions: ['장 건강', '소화 기능', '면역 기능', '영양소 흡수', '정신 건강', '피부 건강'],
    deficiencySymptoms: [
      '소화불량',
      '변비/설사',
      '복부 팽만',
      '면역력 저하',
      '피부 문제',
      '기분 변화',
    ],
    excessSymptoms: ['복부 팽만 (초기)', '가스', '소화불량 (일시적)'],
    foodSources: ['요거트', '김치', '낫또', '템페', '케피어', '사우어크라우트', '된장'],
    recommendedDailyIntake: {
      men: '10억-100억 CFU',
      women: '10억-100억 CFU',
    },
    benefits: [
      '소화 기능 개선',
      '면역력 강화',
      '항생제 부작용 완화',
      '설사/변비 개선',
      '피부 건강',
      '정신 건강',
    ],
    bestTakenWith: ['공복 또는 식사 30분 전', '프리바이오틱스 (식이섬유)'],
    warnings: ['면역 저하자 주의', '냉장 보관', '항생제와 2시간 간격'],
    whoNeedsIt: [
      '소화 문제가 있는 사람',
      '항생제 복용 중인 사람',
      '면역력이 약한 사람',
      '과민성 대장 증후군이 있는 사람',
    ],
  },
];

export const symptomVitaminMap: Record<string, string[]> = {
  피로: ['vitamin-b12', 'vitamin-d', 'iron', 'magnesium', 'vitamin-b1'],
  '근육 경련': ['magnesium', 'vitamin-d', 'calcium', 'vitamin-e'],
  우울증: ['vitamin-d', 'vitamin-b6', 'vitamin-b9', 'omega-3', 'magnesium'],
  불면증: ['magnesium', 'vitamin-d', 'vitamin-b6'],
  '면역력 저하': ['vitamin-c', 'vitamin-d', 'zinc', 'vitamin-a', 'probiotics'],
  빈혈: ['iron', 'vitamin-b12', 'vitamin-b9', 'vitamin-b2'],
  '피부 건조': ['vitamin-a', 'vitamin-e', 'omega-3', 'vitamin-c'],
  탈모: ['iron', 'zinc', 'vitamin-d', 'vitamin-b9'],
  '기억력 감퇴': ['vitamin-b12', 'omega-3', 'vitamin-d', 'vitamin-b6'],
  '시력 저하': ['vitamin-a', 'vitamin-c', 'vitamin-e', 'omega-3'],
  '잇몸 출혈': ['vitamin-c', 'vitamin-k'],
  '상처 회복 느림': ['vitamin-c', 'zinc', 'vitamin-e', 'vitamin-a'],
  '손발 저림': ['vitamin-b12', 'vitamin-b1', 'calcium', 'magnesium'],
  '소화불량': ['probiotics', 'vitamin-b3', 'magnesium'],
  '변비/설사': ['probiotics', 'magnesium', 'vitamin-c'],
  '두통/편두통': ['magnesium', 'vitamin-b2', 'vitamin-d'],
  '생리전 증후군': ['vitamin-b6', 'calcium', 'magnesium', 'vitamin-e'],
  '여드름': ['zinc', 'vitamin-a', 'probiotics'],
  '관절통': ['omega-3', 'vitamin-d', 'calcium'],
  '눈 건조': ['vitamin-a', 'omega-3'],
};

export function getVitaminsBySymptoms(symptoms: string[]): Vitamin[] {
  const vitaminIds = new Set<string>();

  symptoms.forEach(symptom => {
    const vitamins = symptomVitaminMap[symptom];
    if (vitamins) {
      vitamins.forEach(id => vitaminIds.add(id));
    }
  });

  return vitamins.filter(v => vitaminIds.has(v.id));
}
